### ISSUE TITLE
Create basic event style guide (template)

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#22]
### Test for Luis on PRODUCTION
- [ ] Looks ok on iphone 
- [ ] Looks ok ipad mini
- [ ] Looks good enough at desktop
- [ ] Works ok on Firefox
- [ ] Works ok on Chrome
- [ ] Works ok on IE 10

### Sign off for Lou  on PRODUCTION - in order they appear on the page - ENGLISH
- [x] Place holder header image
- [x] Logo appears
- [x] Strap-line appears
- [x] Event title (on shaded area over image)
- [x] Event date (on shaded area over image)
- [x] Start time and end time (on shaded area over image)
- [x] Price 
- [x] Event types (separated by a pipe)
- [x] Short event description
- [x] Event amenities (full list) separated by a vertical pipe
- [x] Contact phone number 
- [x] Heading for location (Location)
- [x] Link to business unit
- [x] Address
- [x] Map with location pin
- [x] Horizontal page divide 'more events'

## Premium events listing on basic event page
- [x] Image
- [x] Time
- [x] Event title
- [x] Event location (@Business unit name or @location)
- [x] Event excerpt
- [x] Horizontal line

### Sign off for Lou - in order they appear on the page - SPANISH
- [x] Toggle to spanish version
- [x] Place holder header image
- [x] Logo appears
- [x] Strap-line appears
- [x] Event title (on shaded area over image)
- [x] Event date (on shaded area over image)
- [x] Start time and end time (on shaded area over image)
- [x] Price 
- [x] Event types (separated by a pipe)
- [x] Short event description
- [x] Event amenities (full list) separated by a vertical pipe
- [x] Contact phone number 
- [x] Heading for location (Location)
- [x] Link to business unit
- [x] Address
- [x] Map with location pin
- [x] Horizontal page divide 'more events'

## Premium events listing on basic event page
- [x] Image
- [x] Time
- [x] Event title
- [x] Event location (@Business unit name or @location)
- [x] Event excerpt
- [x] Horizontal line

**Comment by angievanhegan** [comment]
- there's not a short event description and we've got it in the acceptance criteria. Should there really be one?

**Comment by lolmos** [comment]
### Subjective comment (only do something if you feel very strongly)
1.  *it feels like there's a lot of horizontal black lines at the bottom of the page (I think the 'other events like this right next to the tomorrow line looks funny). I feel like the 'other related event's' title should be a bit different and perhaps more solid. In my head, it should be more like the 'see all events' button as it's serving a similar function.* 
	- made the first heading an h3 instead of an h4. gonna leave it for now


2. *where you use @ to explain the venue, it makes me think it's their twitter handle (mostly because I'm an ignorant idiot. But so are a lot of other people!)*
	- will see this with the testing

	
3. *I think the name of the event (for the related events) should have much more emphasis*
	- going to keep it as is, this ight get crowded, and needs to be the same as on events pages

	  
4. *I'm not keen on the centre align of the related event text. It feels out of kilter with the rest of the site.*
	- stays

5. *overall, the related events bit feels a bit squished to me (I think the date in the horizontal line could do with a bit more space above it)*
	- might test for diferent sizes

	
6. *it feels like the images on the related events should fully cover the white bit (and not have white below and above them). It might look nice without the white background?*
	- no, events should not look like business units. reading text on different images is a nightmare.

7. *I wonder if the bottom of the page should have a 'see all events' button again?*
	- yes, done it 

### Issues
1. *there's no phone number (we should add one so it can be tested etc)*
	- test with the saturday cinema
 
2. *Chrome: it looks like there should be more space below the first horizontal line and before the short description*
 -	fixed
  
3. *Chrome, iphone, iPad horizontal only: The bottom of the tab for the map details is cut off*
	- should work now as the map is larger and have reduced space around popup

4. *There's no link to the business unit, or the address in the content, only on the map. Is this right? I'm going from the acceptance criteria boxes above*
	- only if the event has an existing business unit linke to it should it appear
	- try: [salsa lessons](https://holboxeno.dev:8890/en/events/2016/09/09/salsa-lessons-with-cesar.html)

**Comment by angievanhegan** [comment]
@lolmos 

- The phone number doesn't try to open Facebook
- There's not as much space under the first horizontal line and the description below it as there is on the premium page
