### ISSUE TITLE
Create Premium event style guide (template)

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#23]
#22 should be done before this:

__Test for Angie on PRODUCTION__
- [x] Looks ok on iphone 5
- [x] Looks ok ipad mini
- [x] Looks good enough at desktop
- [x] Works ok on Firefox
- [x] Works ok on Chrome
- [ ] Works ok on IE 10

## Has fields for the following meta data tags
- [x] Meta description
- [x] Meta title
- [x] OG title
- [x] OG description
- [x] Twitter title
- [x] Twitter description (raised as #77)

__
- [x] Has all the info from a basic event
- [x] Has a longer description
- [x] Has it's own header image
- [x] Does not have any additional event at the bottom of the page

**Comment by angievanhegan** [comment]
### Subjective feedback (only act on these if you feel strongly)
Add an issue to the backlog if you want to do them later. 
- I wonder if the event tags at the top need a title?  A one/two work intro. Something like "Event type:" but better.  They're quite high up the page. Is this the 5th most important piece of info? I think the description would be more important to me as a user. Also, I wanted to be able to click them! 
-  Personally, I think the pipe at the end of the line is redundant. It doesn't add anything.  Same applies on the venue facilities
- I think the venue facilities might need a title.  Why is there a TV at a salsa night?
- I wonder if the venue name should have more priority on the tab on the map? 
- Seeing as in Holbox, people seem to navigate in relation to other places and not street names (e.g. we live opposite La Changa) that it might be a nice feature in the future to be able to add other landmarks to the map to help you work out where the place your'e looking for is
- Does the street name above the map add much (in a place that doesn't really use them). I suspect people can easily read if off the map. When I read 'sin numero' it feels a tiny bit like an error message. 
- Could you add the copyright info for the map underneath the area taken up by the map so that the label would never overlap it? 

### Requsts

- can we rename the "restaurant 9 premium' page to Tribu so that this is done? Otherwise its just one more thing to come back and do later. 

## Issues
- Chrome: When I zoom, the top yellow block expands much wider than the grey text area below it and I lose it off the screen
- Firefox: The bottom strip of the label on the map isn't shown (I can only see the top of the numbers
-  iPhone: time and date overlap slightly.
- iPhone: When I first viewed the page, the bottom of the map label was cut off. The second time, I was zoomed in on the sea. Not sure what I'd done.

**Comment by lolmos** [comment]
## feedback
- _I think I'd like to see the price include the currency. If you're away from home, your'e constantly befuddled by money, and every little bit of clarity helps. Also, sometimes (like with yoga) you've explicitly expressed the price in USD so it'd be good to be confident it's pesos, when it is pesos._

  - that goes in the CMS the currency is entered manually. 

- _I think there should be a space in price after the colon_
 - done

- _ if you did the time in 24 hour clock it'd take up less space (do you use PM and AM in Spanish?)_
 _  need to check. my feeling is that most US and Mex people aren't used to 24hr clock

- _I wonder if the event tags at the top need a title? A one/two work intro. Something like "Event type:" but better. They're quite high up the page. Is this the 5th most important piece of info? I think the description would be more important to me as a user. Also, I wanted to be able to click them!_
 - need to look at this in the future

- _Personally, I think the pipe at the end of the line is redundant. It doesn't add anything. Same applies on the venue facilities. If you have it though, you need to make sure it can't sit on a new line on it's own_
 - been wanting to do this for all lists- done it now. we need to see if we can add labels to the list. can't really control whether or not you get a strangler(maybe with a nonbreaking space)

**Comment by lolmos** [comment]
### Requests

-  _can we rename the "restaurant 9 premium' page to Tribu so that this is done? Otherwise its just one more thing to come back and do later. _
- done


- _Salsa event in Spanish has the precio as  'free' - can you make sure the system doesn't let you do this?_
-  fixed, was an entry error


- _Can you have your CMS make sure that when you add event category or a venue amenity it always starts with a capital letter. you've missed one (spa) and it doesn't look so pretty._
- fixed the Typo. made an issue (write regular expression)
 

- _yoga is missing a venue_
 -  fixed, it was a bug

**Comment by lolmos** [comment]
## Issues
-  _Chrome: When I zoom, the top yellow block expands much wider than the grey text area below it and I lose it off the screen. Yellow header isn't the same width as the grey text area below _

fixed


-  _ iPhone: time and date overlap slightly on yellow area_

 can't see this anymore can you send a screen grab?



-  _Firefox, iPad (horizontal), iPhone: The bottom strip of the label on the map isn't shown (I can only see the top of the numbers_

please include a screengrab. can't replicate. it works ok on mine maybe you had moved the map around before you changed orientation



-  _There's no twitter description content_
seems to be a bug 

should there be content in all the other header fields that you built?_
I've made it so that if there aren't' og and twitter fields then nothing is shown, I'm working on the premise that the premiums will have to have it written but the basics can not have it so we can start getting the content up

**Comment by angievanhegan** [comment]
@lolmos All looks *great* to me. You just need to check the issues in IE10
